In [83]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd

In [131]:
# load freetrade stocks
investments = context.catalog.load('investments_raw')

2021-02-14 11:20:23,453 - kedro.io.data_catalog - INFO - Loading data from `investments_raw` (CSVDataSet)...

In [132]:
investments.head()

,Symbol,Name,DisplaySymbol,Exchange,Portfolio,Currency,Quantity,Cost Per Share,Cost Basis Method,Commission,Date,TimeOfDay,PurchaseFX,Type,Notes
0,ISF.L,Ishares Plc Ishares Core Ftse10,FTSE 100,LSE,ISA,GBp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ISF.L,Ishares Plc Ishares Core Ftse10,FTSE 100,LSE,ISA,GBp,35.0,570.0,0.0,0,2020-09-21 GMT+0100,17:38:00,NaN,Buy,NaN
2,ISF.L,Ishares Plc Ishares Core Ftse10,FTSE 100,LSE,ISA,GBp,91.0,549.3,0.0,0,2020-10-30 UTC,18:57:00,NaN,Buy,NaN
3,ISF.L,Ishares Plc Ishares Core Ftse10,FTSE 100,LSE,ISA,GBp,434.0,641.0,0.0,0,2020-12-24 UTC,19:59:00,NaN,Dividend,NaN
4,IUKD.L,Ishares Plc Ishares Uk Dividend,NaN,LSE,GIA,GBp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
# remove .L from symbols
investments['symbol_ft'] = investments.Symbol.str.replace(r'.L$', '')

In [135]:
# identify exchanges
investments.Exchange.unique()

array(['LSE', 'NMS', 'NYQ'], dtype=object)

In [136]:
# remap exchange column, to match column used in ETFs
investments['stock_exchange'] = investments.Exchange.replace({'LSE': 'London', 'NMS': 'NASDAQ', 'NYQ': 'NYSE'})

In [137]:
# check columns
investments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Symbol             276 non-null    object
 1   Name               276 non-null    object
 2   DisplaySymbol      143 non-null    object
 3   Exchange           276 non-null    object
 4   Portfolio          276 non-null    object
 5   Currency           276 non-null    object
 6   Quantity           231 non-null    float64
 7   Cost Per Share     231 non-null    float64
 8   Cost Basis Method  231 non-null    float64
 9   Commission         231 non-null    object
 10  Date               231 non-null    object
 11  TimeOfDay          231 non-null    object
 12  PurchaseFX         5 non-null      float64
 13  Type               231 non-null    object
 14  Notes              10 non-null     object
 15  symbol_ft          276 non-null    object
 16  stock_exchange     276 non-null    object
dtypes: float64(4), object(13)
memory usage: 36.8+ KB

In [138]:
# remove blank rows
investments[~investments.Type.isna()]

,Symbol,Name,DisplaySymbol,Exchange,Portfolio,Currency,Quantity,Cost Per Share,Cost Basis Method,Commission,Date,TimeOfDay,PurchaseFX,Type,Notes,symbol_ft,stock_exchange
1,ISF.L,Ishares Plc Ishares Core Ftse10,FTSE 100,LSE,ISA,GBp,35.000,570.00,0.0,0,2020-09-21 GMT+0100,17:38:00,NaN,Buy,NaN,ISF,London
2,ISF.L,Ishares Plc Ishares Core Ftse10,FTSE 100,LSE,ISA,GBp,91.000,549.30,0.0,0,2020-10-30 UTC,18:57:00,NaN,Buy,NaN,ISF,London
3,ISF.L,Ishares Plc Ishares Core Ftse10,FTSE 100,LSE,ISA,GBp,434.000,641.00,0.0,0,2020-12-24 UTC,19:59:00,NaN,Dividend,NaN,ISF,London
5,IUKD.L,Ishares Plc Ishares Uk Dividend,NaN,LSE,GIA,GBp,11.000,717.45,0.0,0,2019-08-05 GMT+0100,00:00:00,NaN,Buy,NaN,IUKD,London
6,IUKD.L,Ishares Plc Ishares Uk Dividend,NaN,LSE,GIA,GBp,13.000,715.65,0.0,0,2019-08-07 GMT+0100,00:00:00,NaN,Buy,NaN,IUKD,London
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,ISP6.L,Ishares Iii Plc Ishrs S&p Smll,S&P SmallCap 600,LSE,GIA,GBp,291.000,5864.00,0.0,0,2021-01-30 UTC,23:57:00,NaN,Dividend,NaN,ISP6,London
270,ISP6.L,Ishares Iii Plc Ishrs S&p Smll,S&P SmallCap 600,LSE,GIA,GBp,13.000,5908.00,0.0,0,2021-02-04 UTC,15:04:00,NaN,Sell,NaN,ISP6,London
272,OPEN,Opendoor Technologies Inc,Opendoor,NMS,GIA,USD,21.997,19.80,0.0,0,2020-11-09 UTC,16:45:00,0.763475,Buy,NaN,OPEN,NASDAQ
273,OPEN,Opendoor Technologies Inc,Opendoor,NMS,GIA,USD,21.000,28.62,0.0,0.45%,2021-02-04 UTC,15:54:00,NaN,Sell,NaN,OPEN,NASDAQ
274,OPEN,Opendoor Technologies Inc,Opendoor,NMS,GIA,USD,0.997,28.68,0.0,0.45%,2021-02-04 UTC,15:55:00,NaN,Sell,NaN,OPEN,NASDAQ

In [170]:
# consider only Type buy or sell with intention of extracting only current holdings
holdings = investments[investments.Type.isin(['Buy', 'Sell'])]

In [173]:
# convert Quantity to negative when stocks are sold

holdings['type_num'] = holdings.Type.replace({'Buy': 1, 'Sell': -1})

holdings.eval('Quantity = type_num * Quantity', inplace=True)

In [176]:
# sum total stocks sold and bought to identify current holdings
holdings = holdings.groupby(['symbol_ft', 'stock_exchange'])['Quantity'].sum()

In [178]:
# filter only current holdings
holdings = holdings[holdings > 0]

In [180]:
holdings = (
    holdings
    .reset_index()
    .rename({'Quantity': 'shares_held'}, axis=1)
)
holdings

   symbol_ft stock_exchange  shares_held
0       ERNS         London     2.000000
1       IDVY         London   232.000000
2       IGLS         London     2.000000
3       INFR         London    22.000000
4       IPOE           NYSE    12.552000
5        ISF         London   657.000000
6       ISP6         London    12.000000
7       IUKD         London   369.000000
8       IUKP         London   229.000000
9       IWDP         London    64.000000
10       JDW         London    24.000000
11       KHC         NASDAQ    21.061955
12        KO           NYSE    12.000000
13      OPEN         NASDAQ     5.936012
14      SEMB         London     3.000000
15      SEML         London    10.000000
16      SSHY         London     5.000000
17      TSLA         NASDAQ     1.000000
18      USDV         London    93.000000
19      VHYL         London    14.000000
20      VJPN         London    22.000000
21      VMID         London   112.000000

In [165]:
# load etfs list for checking matches
etfs = context.catalog.load('etfs')

2021-02-14 12:23:57,221 - kedro.io.data_catalog - INFO - Loading data from `etfs` (CSVDataSet)...

In [181]:
# join holdings onto ETFs to ensure all matching
merged = pd.merge(etfs, holdings, on=['symbol_ft', 'stock_exchange'], how='outer')

In [182]:
# identify stocks which have not matched
merged[merged['title'].isna()]

,title,long_title,subtitle,currency,isa_eligible,isin,mic,symbol_ft,fractional_enabled,plus_only,...,for_netherlands_investors,kiid_url,stock_exchange,country,symbol,full_name,name,asset_class,def_stock_exchange,shares_held
179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IPOE,NaN,NaN,...,NaN,NaN,NYSE,NaN,NaN,NaN,NaN,NaN,NaN,12.552000
180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JDW,NaN,NaN,...,NaN,NaN,London,NaN,NaN,NaN,NaN,NaN,NaN,24.000000
181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KHC,NaN,NaN,...,NaN,NaN,NASDAQ,NaN,NaN,NaN,NaN,NaN,NaN,21.061955
182,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KO,NaN,NaN,...,NaN,NaN,NYSE,NaN,NaN,NaN,NaN,NaN,NaN,12.000000
183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OPEN,NaN,NaN,...,NaN,NaN,NASDAQ,NaN,NaN,NaN,NaN,NaN,NaN,5.936012
184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SSHY,NaN,NaN,...,NaN,NaN,London,NaN,NaN,NaN,NaN,NaN,NaN,5.000000
185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TSLA,NaN,NaN,...,NaN,NaN,NASDAQ,NaN,NaN,NaN,NaN,NaN,NaN,1.000000

Only ETF which hasn't matched is SSHY. I suspect this is simply not included in the investing.com roster, but requires a little bit of investigation to identify the reason. All the others are stocks which are not yet included in this analysis.

To ensure this is not missed it will be included in the sell report with an unknown status, alongside the other asset classes.